# Generated by Django 5.2.6 on 2025-09-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(choices=[('sepatu', 'Sepatu'), ('baju', 'Baju'), ('celana', 'Celana'), ('raket', 'Raket'), ('bola', 'Bola')], default='baju', max_length=20),
        ),
    ]
