# Generated by Django 5.2.6 on 2025-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_2',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
