# Generated by Django 5.2.6 on 2025-09-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_price_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_2',
        ),
    ]
